adaptive: true
affinity: socket_unique_interleaved
amp: apex
apex_amp_opt_level: O2
append_dataset: false
append_time: false
attn_type: 0
batch_chunk: 4
batch_size: 256
clamp_len: -1
clip: 0.25
clip_nonemb: false
cuda: true
cutoffs:
- 19997
- 39997
- 199997
- 267736
d_embed: 256
d_head: -1
d_inner: 1101
d_model: 256
dataset: wt103
debug: false
decay_rate: 0.5
div_val: 1
dllog_file: train_log.json
dropatt: 0.0
dropout: 0.1
dtype: null
emb_init: normal
emb_init_range: 0.01
eta_min: 0.001
eval_batch_size: 16
eval_interval: 5000
eval_max_steps: -1
eval_tgt_len: 192
experiment_name: nv_xformer_xl
ext_len: 0
fear_terminate: false
fp16: false
get_params: false
gpu0_bsz: -1
init: normal
init_range: 0.1
init_std: 0.02
local_batch_size: null
local_rank: 0
log_all_ranks: false
log_interval: 10
lr: 0.01
lr_min: 0.0
max_step: 40000
max_step_scheduler: null
mem_len: 192
mom: 0.0
multi_gpu: ddp
n_all_param: 74172073
n_head: 2
n_layer: 6
n_nonemb_param: 5362638
n_token: 267736
no_env: true
no_eval: false
not_tied: false
optim: jitlamb
patience: 0
pre_lnorm: false
primer_conv: false
primer_square: false
proj_init_std: 0.01
restart: ''
roll: true
same_length: false
sample_softmax: -1
save_all: false
scheduler: cosine
seed: 1111
swap_mem: false
target_perplexity: null
target_throughput: null
tgt_len: 192
tie_projs:
- false
- true
- true
- true
tie_weight: true
tied: true
txtlog_file: train_log.log
use_cache: false
use_train: false
varlen: false
vocab: word
vocab_size: null
warmup_step: 1000
weight_decay: 0.0
weight_init_range: 0.1
weight_init_std: 0.02
weight_init_type: normal
