batch: 1000
config_file: wt103_base.yaml
crossover_size: 4
d_inner_choice:
- 512
- 562
- 612
- 662
- 712
- 762
- 812
- 862
- 912
- 962
- 1012
- 1062
- 1112
- 1162
- 1212
- 1262
- 1312
- 1362
- 1412
- 1462
- 1512
- 1562
- 1612
- 1662
- 1712
- 1762
- 1812
- 1862
- 1912
- 1962
- 2012
- 2048
- 2248
- 2448
- 2648
- 2848
- 3048
d_model_choice:
- 128
- 256
- 512
- 650
- 800
default_path: ./evo_search
device_name: XeonE5-2690
do_train: false
eps: 0.05
experiment_name: evolution
gpu_config: dgx1_1gpu_fp32
hybrid: false
latency_constraint: 10.0
latency_repeat: 5
latency_scale: 2.0
max_step: 500
model_type: mem_transformer
mutation_prob: 0.3
mutation_size: 4
n_gpus: 1
n_head_choice:
- 2
- 4
- 8
n_iter: 10
n_layer_choice:
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
n_threads: 1
nsamples: 20000
param_constraint: 5000000.0
parent_size: 2
pareto_search: true
phase: run_search
population_size: 10
results_path: ./evo_search/param_threshold_5.0_pareto_XeonE5-2690
scheduler: constant
seed: 1111
start_train: 40
train_local: false
use_convex_hull: false
use_valid: false
