adaptive: true
attn_type: 0
clamp_len: -1
cutoffs:
- 19997
- 39997
- 199997
- 50264
d_embed: 512
d_head: -1
d_inner:
- 549
- 1851
- 1660
- 897
- 1410
- 1156
- 612
- 1624
- 1443
- 1521
- 1296
- 1876
- 806
- 796
d_model: 256
div_val: 2
dropatt: 0.0
dropout: 0.1
dtype: null
ext_len: 0
mem_len: 192
n_head:
- 8
- 4
- 8
- 8
- 4
- 8
- 2
- 8
- 8
- 4
- 8
- 2
- 2
- 2
n_layer: 14
n_token: 50264
pre_lnorm: false
primer_conv: false
primer_square: false
proj_init_std: 0.01
same_length: false
sample_softmax: -1
tgt_len: 192
tie_projs:
- false
- true
- true
- true
tie_weight: true
use_cache: false
weight_init_range: 0.1
weight_init_std: 0.02
weight_init_type: normal
