adaptive: true
attn_type: 0
clamp_len: -1
cutoffs:
- 19997
- 39997
- 199997
- 50264
d_embed: 128
d_head: -1
d_inner:
- 1748
- 1709
- 1624
- 2002
- 1011
- 2019
- 991
- 1136
- 1925
- 1846
d_model: 256
div_val: 2
dropatt: 0.0
dropout: 0.1
dtype: null
ext_len: 0
mem_len: 192
n_head:
- 4
- 8
- 2
- 4
- 4
- 2
- 8
- 2
- 4
- 2
n_layer: 10
n_token: 50264
pre_lnorm: false
primer_conv: false
primer_square: false
proj_init_std: 0.01
same_length: false
sample_softmax: -1
tgt_len: 192
tie_projs:
- false
- true
- true
- true
tie_weight: true
use_cache: false
weight_init_range: 0.1
weight_init_std: 0.02
weight_init_type: normal
