__include__: 'darts.yaml' # just use darts defaults


nas:
  search:
    model_desc:
      num_edges_to_sample: 2 # number of edges each node will take input from

  eval:
    natsbench:
      arch_index: 9682
      natsbench_tss_fast: 'NATS-tss-v1_0-3ffb9-simple' # folder name in dataroot/natsbench that contains the tss fast mode folder
    model_desc:
      num_edges_to_sample: 2
    loader:
      train_batch: 1024 # natsbench uses 256
      aug: '' # random flip and crop are already there in default params
    trainer: # matching natsbench paper closely
      phase_identifiers: [[stem.0, stem.1, cells.0], [cells.1], [cells.2], [cells.3], [cells.4], [cells.5], [cells.6], [cells.7], [cells.8], [cells.9], [cells.10], [cells.11], [cells.12], [cells.13], [cells.14], [cells.15], [cells.16,lastact,classifier]]
      num_epochs_per_phase: 1
      plotsdir: ''
      apex:
        _copy: '/common/apex'
      aux_weight: '_copy: /nas/eval/model_desc/aux_weight'
      drop_path_prob: 0.2 # probability that given edge will be dropped
      grad_clip: 5.0 # grads above this value is clipped
      l1_alphas: 0.0   # weight to be applied to sum(abs(alphas)) to loss term
      logger_freq: 1000 # after every N updates dump loss and other metrics in logger
      title: 'eval_train'
      epochs: 200
      batch_chunks: 1 # split batch into these many chunks and accumulate gradients so we can support GPUs with lower RAM
      lossfn:
        type: 'CrossEntropyLoss'
      optimizer:
        type: 'sgd'
        lr: 0.1 # init learning rate
        decay: 5.0e-4 # pytorch default is 0.0
        momentum: 0.9 # pytorch default is 0.0
        nesterov: True # pytorch default is False
        decay_bn: .NaN # if NaN then same as decay otherwise apply different decay to BN layers
      lr_schedule:
        type: 'cosine'
        min_lr: 0.000 # min learning rate to be set in eta_min param of scheduler
        warmup:  # increases LR for 0 to current in specified epochs and then hands over to main scheduler
          multiplier: 1
          epochs: 0 # 0 disables warmup
  
    
    